language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "pPBI8hO3hxTeU2xk+iNB7tK6MlKmayqdizsUf9CceeEfO00f4Z/vaQCfiCeLdzSM4+HRpFH9U5tLbPR3P/eame6D0FEWtA7g5ZYo5ozgXTFQGJgcSq4DfP0xc0cRklaQAAK8fBi8TY4Kd8/Cad2KftFzNAAl/anirtVak16Nz/VY4OxIKb+OMba+6rL/7o9Q2msNKigdEUcYA2savZWa/GCuSPwXxPZ0jaKF2uqsvqcCSBbEn4qagyOOI0zXRraGqggRgiR2vaPdnz+ehrkJgNXIk7lrelXdOirip7UvQOvWXxlKin6yF1vJYeKrPh6MqsJFWZ8VU+r+ZNtITPa77SlVTBIWN+CvpF+39gBYu8ga4AM7COvSNkfxZj0HaP3ZMTaq+sMqvKvxfxEW88IddRa1yzy1ABLgPBdMGMmwoi3Cr9Gc+QFOowTHX/C+4mpUGg7OvfNh3Z6vZHlg0wYtZRgJrnd6KVmLx1pVB/gjG86SaZnrJZ6/ymVSHNP4o77+B60ljSRKLNbeX1MHwx/HPWOaUrejdb0QldZBGUqV93pY+ZTEoeERNpPcdeyC+qEEbg5zExDw/KOwPHRJ0DcxNS5qITVhe0SaYOgiZKrL3ptd/Vn2eqiF3HCV2sAEsJ1ttFsuwxilSRmoEuC2HfsBBTs8LCr+6nssMYpHY3rahaM="
  - secure: "PKbapHBYy9/3oRB11GH1CZgdu8ui7dDjF9XzRF2G9DPqD2lDotp+zPu6puwvo8EqRICPIweQ0r+N2FciC1ACOl1Y5ttjN0MZA+U45JYvdUK70Xg17FNgmN7K2mTsxA4Ii57v//0VnfDmYfZYgK80Q6kzK6IqEJuPcriwFfAoYeJJT0ZTbu8aN7g0+Qh7ipzt1RG6WWAfVjDwSk5QkgNCTe2f+IkNfkBx7lznnyuM1TTFMgW8kmT8j/EBw0NGWXMc9R+ex8i46Fl5DymqfupNEtWcqHrr1u0oyNEqJquuk0SnyZEXfHwtD25xybyGfTinfkX+pX6JV8x7ibRqRGnwZOnEX36C8qIIarzl0/nsWGBrq0VmvBptNvWcdRRwv2E+3+SarQz8xcpyBgsWLSOENsyhxSXxKBZ7XIwwM+DkdHtmlKQ7rqi0mR+5FM791S18FmlJE/x4q2fCnTzBlM/gVUQ7/Nv6oB7trKz62c2eLmqZPdrgthWnlMqBFGCY+bIaVpTKXp/SRcEbqaqzLAlKJWkZvjHmG0E/dNdvdug/pVgWgLcIo5ZUTMpO6TtD2EiZocFMM/SPevFGfT7zj9FkMWGV72uitvHHlXXvYBWnal2l3LoTckXOpc84vjFEJo9BlEwCXIzQdIkenAlFxY4Jz55z8PeuTS22J4ybFE3epOo="
  - secure: "BxnYasvqfgEjf6l0XOSD+baknHKnpc3IXG6J8cbtq5PoiuHjsjJhmQajqsMePp8pMgnU5OcvjDCc4HUGoc3oUt4KMDEY/YT+RYFxBbDQuRBVi33kCAn4I9mXx/tYsVv8nWTqxWzwVukud5DK4ibRx81tL2wkNAtKF5NdpMWHxd+3eT2TW504tp9ZYsZl2XRVu6rnosj5PKzRKYhb67s3Ni+dYzTSeOc4TMjtIA5b6lSI9mNtlXKJb33lZXYbbh52laRR5t1kC3Aj96yHxF5q9lVOOI9fwYJ5gve6zLDCozFiT2MgDaf8cvAypBBTYiIdxgAOwYQNf6QQlQUDICfW5l9XDTQCUn+l4r20TkzCddT4pmQfb6mTBI2mRgd77l5QR7zyvEq5mJWKF35G7jMJLKoCebNUF9nkAc6aemCoPrk6HkHDzy5DXMH++ks3gZ9uz5tiyfCzsTTsr9ywqHwTUee5DiTvcNUQqPoOLRrZgHs1tEwbopE+lISaPzyZuEa/Cf1gWg7DZEFNSqn8TeyqCkMKdz6DYbcg/EEkZBG1PBuJeC2FMzoI4vUMkorowvwIbqUw6cB2REL91iunxdbT7Jjs0KLnfjMdLjWdCFbCD2GC1AwfHuiSecaAwbXr1nSl2Mq8YB9BBD72qDIfMF6iyxEMrg5OiFNLKIcV0Ep5WEU="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_ac9d94a7e165_key -iv $encrypted_ac9d94a7e165_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
