language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "pPBI8hO3hxTeU2xk+iNB7tK6MlKmayqdizsUf9CceeEfO00f4Z/vaQCfiCeLdzSM4+HRpFH9U5tLbPR3P/eame6D0FEWtA7g5ZYo5ozgXTFQGJgcSq4DfP0xc0cRklaQAAK8fBi8TY4Kd8/Cad2KftFzNAAl/anirtVak16Nz/VY4OxIKb+OMba+6rL/7o9Q2msNKigdEUcYA2savZWa/GCuSPwXxPZ0jaKF2uqsvqcCSBbEn4qagyOOI0zXRraGqggRgiR2vaPdnz+ehrkJgNXIk7lrelXdOirip7UvQOvWXxlKin6yF1vJYeKrPh6MqsJFWZ8VU+r+ZNtITPa77SlVTBIWN+CvpF+39gBYu8ga4AM7COvSNkfxZj0HaP3ZMTaq+sMqvKvxfxEW88IddRa1yzy1ABLgPBdMGMmwoi3Cr9Gc+QFOowTHX/C+4mpUGg7OvfNh3Z6vZHlg0wYtZRgJrnd6KVmLx1pVB/gjG86SaZnrJZ6/ymVSHNP4o77+B60ljSRKLNbeX1MHwx/HPWOaUrejdb0QldZBGUqV93pY+ZTEoeERNpPcdeyC+qEEbg5zExDw/KOwPHRJ0DcxNS5qITVhe0SaYOgiZKrL3ptd/Vn2eqiF3HCV2sAEsJ1ttFsuwxilSRmoEuC2HfsBBTs8LCr+6nssMYpHY3rahaM="
  - secure: "v8B88heVdrABgYRhW1D+RPt3nOHJCvkaET/K5YvDwf3Z521UkMu8scHrw7yJYzovLXigqTVEbPhH3v+qMHA5PindRMsOh0BAnuXCUDGyTQ/Yv6zxs8FzEu5gS6xDGfC3U/C6WNLSF3T6JOQmySyatAd0Pq+BuuySTqZ2TbREysZhSJlgXjVtBW6IsfFohiy5eelLwegncRUPSqQ/+Dlk4AHQFlFOVNZb4B1lmHGZm7bfgyuu8X4Xm5ARkYSbma1LK4WNiEhpmUa2x0JQ45LY+4ueHjcW9vdIhiImdrRi+teAWrepXeNKslvYYFV8YTltCm7Olfw1GAy35T8zAr90Dyu9xsG0Gb0c/g3CDXMdUzZU+oFRdsqwN9eCoaXOxiLh8eGkE3abGB3zQXBMdQPSjjK9FE2J/c23WTN4iPI9gx1i/lnTLbtcJZ0gm21IiOGovaCxKa3W7BYu7S7ClDgc1jc+2U7g9arICT8DrrtYqRkDiaoL1S2fnAUdxa3ed17KfCYAw3q9ZISpdVp/bZyg5Zx0kjnCTyu+oSQYEiEzHcLwvUJ753lEfp0K4bShlqGkm7135O/XH9m6Bq5L0XlRwbMKQ8HqqFSR9IGOk6zyxYyO1FdnUFluV9vNbKdR7HB2hRXOqwmQogCxdJGRBgPDK3ef1d5GLDvLYAxfE8en8F4="
  - secure: "BxnYasvqfgEjf6l0XOSD+baknHKnpc3IXG6J8cbtq5PoiuHjsjJhmQajqsMePp8pMgnU5OcvjDCc4HUGoc3oUt4KMDEY/YT+RYFxBbDQuRBVi33kCAn4I9mXx/tYsVv8nWTqxWzwVukud5DK4ibRx81tL2wkNAtKF5NdpMWHxd+3eT2TW504tp9ZYsZl2XRVu6rnosj5PKzRKYhb67s3Ni+dYzTSeOc4TMjtIA5b6lSI9mNtlXKJb33lZXYbbh52laRR5t1kC3Aj96yHxF5q9lVOOI9fwYJ5gve6zLDCozFiT2MgDaf8cvAypBBTYiIdxgAOwYQNf6QQlQUDICfW5l9XDTQCUn+l4r20TkzCddT4pmQfb6mTBI2mRgd77l5QR7zyvEq5mJWKF35G7jMJLKoCebNUF9nkAc6aemCoPrk6HkHDzy5DXMH++ks3gZ9uz5tiyfCzsTTsr9ywqHwTUee5DiTvcNUQqPoOLRrZgHs1tEwbopE+lISaPzyZuEa/Cf1gWg7DZEFNSqn8TeyqCkMKdz6DYbcg/EEkZBG1PBuJeC2FMzoI4vUMkorowvwIbqUw6cB2REL91iunxdbT7Jjs0KLnfjMdLjWdCFbCD2GC1AwfHuiSecaAwbXr1nSl2Mq8YB9BBD72qDIfMF6iyxEMrg5OiFNLKIcV0Ep5WEU="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_ac9d94a7e165_key -iv $encrypted_ac9d94a7e165_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
